# Generated by Django 2.1.7 on 2019-04-28 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('ip', models.CharField(max_length=100, verbose_name='IP地址')),
                ('username', models.CharField(default='unknown', max_length=100, verbose_name='用户名')),
                ('pw', models.CharField(default='unknown', max_length=100, verbose_name='密码')),
                ('app_username', models.CharField(default='unknown', max_length=100, verbose_name='应用登录名')),
                ('app_pw', models.CharField(default='unknown', max_length=100, verbose_name='应用登录密码')),
                ('note', models.CharField(default='无', max_length=500, verbose_name='备注')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_user', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='update_user', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '密码管理',
                'verbose_name_plural': '密码管理',
            },
        ),
    ]
