# Generated by Django 2.1.7 on 2019-06-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='app_pw',
            field=models.CharField(default='-', max_length=100, verbose_name='应用登录密码'),
        ),
        migrations.AlterField(
            model_name='record',
            name='app_username',
            field=models.CharField(default='-', max_length=100, verbose_name='应用登录名'),
        ),
        migrations.AlterField(
            model_name='record',
            name='note',
            field=models.CharField(default='-', max_length=500, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='record',
            name='pw',
            field=models.CharField(default='-', max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='record',
            name='username',
            field=models.CharField(default='-', max_length=100, verbose_name='用户名'),
        ),
    ]
